go-gorm/datatypes

- json.go
- json_test.go
This PR is to MarshalJSON the datatypes.JSON type w/out base64 encoded []byte.  For example when retrieving database content w/ gorm, and serving a http json response.
more info:  https://groups.google.com/forum/#!topic/Golang-Nuts/38ShOlhxAYY
Before:
```json
{
"Name": "json-1",
"Attributes": "eyJhZ2UiOiAxOCwgIm5hbWUiOiAianNvbi0xIiwgIm9yZ3MiOiB7Im9yZ2EiOiAib3JnYSJ9LCAidGFncyI6IFsidGFnMSIsICJ0YWcyIl19"
}
```
After:
```json
{
"Name": "json-1",
"Attributes": {
"age": 18,
"name": "json-1",
"orgs": {
"orga": "orga"
},
"tags": [
"tag1",
"tag2"
]
}
}
```
> Implement MarshalJSON to output non-base64 encoded []byte

- json.go
- json_test.go
This PR is to allow unmarshaling of datatypes.JSON for example when unmarshaling a `UserWithJSON{}` from a request body `{"name": "json-1", "attributes": {"age":18,"name":"json-1","orgs":{"orga":"orga"},"tags":["tag1","tag2"]}}`.
Before:
```
cannot unmarshal object into Go value of type datatypes.JSON
```
After:
```
{
"name": "json-1",
"attributes": {
"age": 18,
"name": "json-1",
"orgs": {
"orga": "orga"
},
"tags": [
"tag1",
"tag2"
]
}
}
```
> Support UnmarshalJSON of datastypes.JSON

- date.go
- date_test.go
Allow to encode/decode `Date` using encoding/gob and encoding/json
Encode/decode struct that contains `datatypes.Date` fields
> support  json & gob encoding for Date

- json.go
- json_map.go
- [] Do only one thing
- [] Non breaking API changes
- [] Tested
While fetching null value from the DB, Scan() throws an error like this: `2021/06/22 02:54:11 /Users/krishna.birla/Repos/rp-manager/pkg/store/sqlstore/sqlstore.go:89 sql: Scan error on column index 0, name "admins": Failed to unmarshal JSON value:<nil>`
For example, if your JSON or JSONMap field is `default:null`, it fails to Scan() it.
> Fix unmarshal error in JSON/JSONMap scan for null values

- json.go
- json_map.go
when the filed's value is datatypes.JSON{}, it will be error when insert. Because the filed's value
is a empty string instead of NULL.
fix #99
- [] Do only one thing
- [] Non breaking API changes
- [☑️] Tested
I think it a bug.
The table defined:
```
type User struct {
Name string
Email datatypes.JSON
}
```
Then i insert a value.
```
u := User {
Name: "adsa",
Email: datatypes.JSON{},
}
db.Create(&u)
```
The sql will be generated:
```
INSERT INTO `users` (`name`,`email`) VALUES ('adsa',CAST('' AS JSON))
```
and raise an error:
`
Error 3141: Invalid JSON text in argument 1 to function cast_as_json: "The document is empty." at position 0.
`
I think when `email` is a default value `datatypes.Json{}` or `nil`, the sql value should be `NULL` instead of `""`, the sql should be `CAST(NULL AS …
> fix(json): JSON's value is a empty string when it's empty

- url.go
- url_test.go
- It's boring to repeatedly parse/translate url between db storage and a struct
- So I made a simple valuer/scanner and hope it could be contributed
A proxied resource provider:
```golang
type Resource struct {
ID       uint
Name     string
Storage  datatypes.URL
}
if db.Where("name = ?", "NameOfResource").First(&res).Error != nil{
switch res.Storage.Scheme {
case "file":
f, _ := os.Open(res.Storage.Path)
s, _ := f.Stat()
gin_context.DataFromReader(200,  s.Size(), 'application/octet-stream', f, header)
case "http":
resp := http.Get(res.Storage.String())
gin_context.DataFromReader(200, resp.ContentLength, 'application/octet-stream', resp.Body, header)
}
}
```
> Add a URL type support

- json.go
`Scan` to `datatypes.JSON` [makes a copy](https://github.com/golang/go/blob/a131fd1313e0056ad094d234c67648409d081b8c/src/encoding/json/stream.go#L275), this shouldn't be necessary
model has some big JSON in postgres jsonb, it wastes time and memory to copy
> skip copying when scanning datatypes.JSON

- json.go
- json_test.go
close https://github.com/go-gorm/datatypes/issues/136
We can not use in-place value after this commit https://github.com/go-gorm/datatypes/commit/c244d2875ae06d92f7f0765444f297b8aced0a08
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L3008
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L3286
> fix: json scan can not use in place value

- json.go
- json_test.go
This pull request adds support of `Extract()` for `PostgreSQL` driver, just like it was done for MySQL.
This was actually missing and I need it on a project I am working on.
Thank you!
This method allows to write things like:
```go
DB.Where("? = ?", datatypes.JSONQuery("attributes").Extract("name"), "John")
```
> Added JSON postgresql extract

- README.md
- json_type.go
- json_type_test.go
1. add `type JSONSlice[T any] []T` for generic type slice data.
why not use `JSONType[[]T]` ?  
because `JSONSlice` is good for reflection, but `JSONType` is not.
for example
```golang
type User struct {
Tags  JSONSlice[Tag]
Tags2 JSONType[[]Tag]
}
```
when we use json to marshal the value we can got
```json
{
"tags":  [{"name": "tag1", "score":  1.0}],
"tags2":  [{"name": "tag1", "score":  1.0}]
}
```
but we use other decode/encode/reflect method  to process data (like https://github.com/mitchellh/mapstructure)
it will got an extra `data` level, cause `JSONType` with an extra `Data` Field 
```
{
"tags":  [{"name": "tag1", "score":  1.0}],
"tags2": {
"data": [{"name": "tag1", "score":  1.0}],
}
}
```
golang do not support the generic type alias  like`type JSONType[T any] T`  to auto bind …
> add JSONSlice generic for slice data

- json.go
- json_test.go
Adds prefix (`$.`) to path when building the json_extract expression for sqlite and mysql.
If I correctly read json_extract usages for [SQLite3](https://www.sqlite.org/json1.html#jex) and  [Postgres](https://www.postgresql.org/docs/current/functions-json.html), this prefix should not be added by callers of JSONQuery, since it must not be there for Postgres.
https://github.com/go-gorm/datatypes/blob/a74cb928e9b9ae8435d161c6e4b0afc26d1a0047/json.go#L337
https://github.com/go-gorm/datatypes/blob/a74cb928e9b9ae8435d161c6e4b0afc26d1a0047/json.go#L368
These lines are doing the exact same thing. It more seems a legitimate change for me now.
I was implementing a partial search function for my project which uses sqlite3.
```
db.Where(`? LIKE ?`, …
```
> fix: JSONQuery.Extract for SQLite3 lacking prefix for path

- json_map.go
- json_map_test.go
Use `json.Decoder.UseNumber()` when Scan `[]byte` to `JSONMap`
When scanning `JSONMap` (a.k.a `map[string]interface{}`) from `[]byte`, it returns the incorrect value of `int64` and `uint64` if the value is more than 18 digits. The reason is by default `json.Unmarshal` treat `int64` and `uint64` as `float64` and loses the numeric precision. 
For example
```Golang
content := `{"user_id": 1085238870184050699, "name": "Name of user"}`
obj := make(datatypes.JSONMap)
obj.Scan([]byte(content))
fmt.Print(obj["user_id"])
// before: obj["user_id"] = 1.0852388701840507e+18 <-- incorrect value
// after: obj["user_id"] = 1085238870184050699 <-- correct value
fmt.Print(cast.ToInt64(obj["user_id"])) // use github.com/spf13/cast
// before: obj["user_id"] = 1085238870184050688 <-- incorrect value
// …
```
> Use json.Number when scan to JSONMap

- README.md
- json_type.go
- json_type_test.go
This is a fix MR for https://github.com/go-gorm/datatypes/issues/200
and this cause a little breaking change in JSONType[T] usage
I ever post PR https://github.com/go-gorm/datatypes/pull/174 , but  I didn't have test enough for ALL gorm query API.
this exported `Data T` field worked well in `Find`, `First` method, and added  in json_type_test.go.
and `Data() T` method is not so efficient than directly exported field ,  but it is wrong.
This issue  https://github.com/go-gorm/datatypes/issues/200 give a bad case query in `Pluck`
Gorm found the  input ptr of value `var field = &JSONType[*User]`  is a struct , and have an exported Field `Data T`
so it goto the this Struct's schema.Fields logic, and found this struct's `Data T ` and checked `field.DataType == ""` …
> Draft: fix JSONType[T] Pluck query error

- json.go
- json_test.go
Add Likes function on JSONQueryExpression
`
type UserWithJSON struct {
gorm.Model
Name       string
Attributes datatypes.JSON
}
DB.Create(&User{
Name:       "json-1",
Attributes: datatypes.JSON([]byte(`{"name": "jinzhu", "age": 18, "tags": ["tag1", "tag2"], "orgs": {"orga": "orga"}}`)),
}
var result UserWithJSON
DB.First(&result, datatypes.JSONQuery("attributes").Likes("%jin%", "name"))
`
> feature: add Mysql&Postgres Json Like

- go.mod
- go.sum
- uuid.go
- uuid_test.go
- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
This PR adds datatype for `uuid.UUID` along with supporting tests.
The [Google UUID package](https://github.com/google/uuid) is a very popular package among Go developers. Since it's used so widely and so often, it'll be great to abstract it out as a separate gorm datatype. This came up as per the discussion on [this Gorm PR](https://github.com/go-gorm/gorm/pull/7099) with @a631807682 and @itanken.
> feature: Add datatype for uuid.UUID (Google UUID)

- binuuid.go
- binuuid_test.go
- uuid.go
- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
This adds a new datatype BinUUID, similar to datatypes.UUID but with a major difference being that BinUUID stores the uuid in the database as a binary (byte) array instead of a string. Developers may use either datatypes.UUID or datatypes.BinUUID as per their preference, either storing uuid in the database as a string or as a binary (byte) array respectively.
This new datatype is useful for developers who prefer to store uuid as binary (byte) array in the database for join performance, column size optimization or any other reasons.
> feature: Add datatype BinUUID for uuid as binary storage in DB

- .github/workflows/tests.yml
- binuuid.go
- binuuid_test.go
- test_all.sh
- url_test.go
- uuid.go
- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
Closes https://github.com/go-gorm/datatypes/issues/269. Also fixes failing tests for SQL Server (these seem to have never been run previously due to incorrect dialect name, for example see [this workflow](https://github.com/go-gorm/datatypes/actions/runs/10247540115/job/28346951994#step:6:3)).
Use correct dialect name when running SQL Server tests, so the tests for `sqlserver` are executed.
> Fix SQL Server dialect name to match switch case, update failing SQL Server tests

- json.go
- json_test.go
`JSON_CONTAINS` for MySQL supports using the `path` argument to perform the contain check deeper 
into the target column. This change adds support for the use of path in `JSONArrayExpression.Contains`
**for MySQL dialects only**.
Previously,  `JSONArrayExpression.Contains` can only check if an array JSON column contains a specific 
value. For instance, if we have
```
| json_column |
|-------------|
| [1, 2]      |
```
We can do
```go
JSONArrayQuery("json_column").Contains(1)
```
This gets translated to
```SQL
JSON_CONTAINS(`json_column`, JSON_ARRAY(1))
```
If however, we have a nested array in this column, i.e.
```
| json_column  |
|--------------|
| {"a": [1, 2]}|
```
With the path argument, we can now do
```go
JSONArrayQuery("json_column").Contains(1, "a")
```
which gets translated to …
> feature: support using path for JSON_CONTAINS

- json.go
- json_test.go
Allow users to extract nested values from a JSON column and use `JSON_CONTAINS` to check if the 
extracted value belongs a referenced array. This PR implements this in MySQL (and its derived dialects only).
Suppose we have just a JSON array column
```txt
| json_array |
|------------|
| [1, 2]     |
```
We can now do
```go
JSONArrayQuery("json_array").In([]int{1, 2})
```
which translates to
```sql
JSON_CONTAINS(JSON_ARRAY(1, 2), `json_array`)
```
Suppose we have a JSON column with a nested array as follows
```txt
| json_column |
|-------------|
| {"a": 1}    |
```
We can now do
```go
JSONArrayQuery("json_column").In([]int{1, 2}, "a")
```
which translates to
```sql
JSON_CONTAINS(JSON_ARRAY(1, 2), JSON_EXTRACT(`json_column`, '$.a'))
```
We cannot use `IN` here because [older versions of …
> feature: support IN query clauses for nested JSON columns

- json.go
- json_test.go
Support using path for SQLite JSON array contains queries.
This addresses issue [#216](https://github.com/go-gorm/datatypes/issues/216) to some extent.
If we have
```
| json_column   |
|---------------|
| {"a": [1, 2]} |
```
For SQLite databases, we can now do
```go
JSONArrayQuery("json_column", "a").Contains(1)
```
This gets translated to
```SQL
EXISTS(
SELECT 1 FROM json_each(`json_column`, "$.a") WHERE value=1
) AND json_array_length(`json_column`, "$.a") > 0
```
**Note the additional `json_array_length` check compared to the previous implementation.**
This fixes the inconsistency in the behaviour between the MySQL and SQLite dialects.
Previously, if we have
```
| json_column |
|-------------|
| {"a": 1}    |
```
When we do
```go
JSONArrayQuery("json_column").Contains(1)
```
The where …
> feature: support sqlite contains path queries

- json.go
```golang
set := datatypes.JSONSet("object")
set.Set("test_bool", meta.TestBool)
db.....Update("object", set)
```
执行后结果
```
{ "test_bool": 1}
```
bool 类型直接构造为 SQL，而不是通过 statement AddVar 替换为占位符
只进行了 mysql 的测试
> Fix: mysql JSONSet Build bool type to 1/0，expected true/false
